### ISSUE TITLE
A `nest` example from the documentation is not rendered correctly

### ISSUE THREAD

**Issue by Furetur** [fpottier/pprint#13]
Here's a simple example from the documentation:

```
let x =
  string "begin"
  ^^ nest 2 (hardline ^^ string "work")
  ^^ hardline ^^ string "end"

let _ = PPrint.ToFormatter.pretty 1.0 100 Format.std_formatter x
```

It is stated that it should be rendered as follows:

```
begin
  work
end
```

However, on my machine on `20230830` it is rendered as:

```
begin
 
work
end 
```

This looks like a bug

**Comment by fpottier** [comment]
Hello! I believe that you should surround your code with `Format.open_box 0` and `Format.close_box()`.

That said, mixing the use of `PPrint` and `Format` is discouraged. It is preferable to use one or the other, not both at the same time.

**Comment by Furetur** [comment]
Hello @fpottier! I believe that this is a bug in the library. In the documentation, it states:

> every time a newline character is emitted, it is immediately followed by n blank characters

But in the example I provided `work` is not preceded with 2 blank characters.

Do you disagree?

**Comment by fpottier** [comment]
Yes, I disagree; it is not a bug. Apparently you are not supposed to emit material without first opening a `Format` box. If you do open a box, then you get the desired output.

**Comment by Furetur** [comment]
Could you clarify it a little bit? Am I supposed to open and close the box every time I use `nest` or should it be done only once around the `pretty` function?

**Comment by fpottier** [comment]
If you use `PPrint.ToFormatter`, then yes, I guess you should open one box at the top level, around the call to `pretty`.

But, unless you have a strong reason to use `PPrint.ToFormatter`, I would suggest *not* using the `Format` module together with `PPrint`. Just use `PPrint.ToBuffer` or `PPrint.ToChannel`.

**Comment by mikeshulman** [comment]
It would be useful if the documentation of `ToFormatter` could mention this need for a surrounding box.  I spent a while fighting with it (being forced to interface with `Format` since another library uses it) before discovering this closed issue.

**Comment by fpottier** [comment]
Thanks for this suggestion. I have added this comment. It will appear in the next release.
