### ISSUE TITLE
Fails to build on `4.02.0`

### ISSUE THREAD

**Issue by tperami** [fpottier/pprint#8]
I was just doing some old version tests, and `pprint` fails to build on Ocaml `4.02.0` contrary to what the Opam file claims. I tested with Ocaml `4.04.2` and it worked fine. If you could fix or bump the minimal required version, that would be great. I can test with Ocaml `4.03` if needed.

**Comment by fpottier** [comment]
Thanks for pointing this out! I confirm that I get `Syntax error` with OCaml 4.02. That said, `pprint` works with OCaml 4.02.3, so I will just fix the constraint in our package description file.

**Comment by fpottier** [comment]
Actually, OCaml 4.02.2 is required; this is where `type nonrec` appears. Should be fixed now. Thanks!
